house_of_tea/urls.py
from django.contrib import admin
from django.urls import path, include

from house_of_tea import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("goods.urls", namespace="catalog")),
    path("user/", include("users.urls", namespace="user")),
    path("cart/", include("carts.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main import views

app_name = "main"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("about/", views.AboutView.as_view(), name="about"),
]

orders/urls.py
from django.urls import path

from orders import views

app_name = "order"

urlpatterns = [
    path("create-order/", views.create_order, name="create_order"),
]

orders/models.py
from django.db import models

from users.models import User
from goods.models import Products


class OrderItemQuerySet(models.QuerySet):
    def total_price(self):
        return sum(cart.products_price() for cart in self)

    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0


class Order(models.Model):
    user = models.ForeignKey(
        to=User, on_delete=models.SET_DEFAULT, blank=True, null=True, default=None
    )
    created_timestamp = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата замовлення"
    )
    phone_number = models.CharField(
        max_length=20, verbose_name="Номер телефону замовника"
    )
    requires_delivery = models.BooleanField(
        default=False, verbose_name="Потрібна доставка"
    )
    delivery_address = models.TextField(
        blank=True, null=True, default="Адреса доставки"
    )
    payment_on_get = models.BooleanField(
        default=False, verbose_name="Оплата при отриманні"
    )
    is_paid = models.BooleanField(default=False, verbose_name="Оплачено")
    status = models.CharField(
        max_length=50, default="В обробці", verbose_name="Статус замовлення"
    )

    class Meta:
        db_table = "order"
        verbose_name = "Заказ"
        verbose_name_plural = "Закази"
        ordering = ("id",)

    def __str__(self):
        return f"Замовлення № {self.pk} | Замовник {self.user.first_name} {self.user.last_name}"


class OrderItem(models.Model):
    order = models.ForeignKey(
        to=Order, on_delete=models.CASCADE, verbose_name="Замовлення"
    )
    product = models.ForeignKey(
        to=Products, on_delete=models.SET_DEFAULT, default=None, blank=True, null=True
    )
    name = models.CharField(max_length=150, verbose_name="Назва")
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Ціна")
    quantity = models.PositiveIntegerField(default=0, verbose_name="Кількість")
    created_timestamp = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата продажу"
    )

    class Meta:
        db_table = "order_item"
        verbose_name = "Продані товари"
        verbose_name_plural = "Продані товари"
        ordering = ("id",)

    objects = OrderItemQuerySet.as_manager()

    def product_price(self):
        return round(self.price * self.quantity, 2)

    def __str__(self):
        return f"Замовлення {self.name} | Номер № {self.order.pk}"

orders/forms.py
import re
from django import forms


class CreateOrderForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    phone_number = forms.CharField()
    requires_delivery = forms.ChoiceField(
        choices=[
            ("0", False),
            ("1", True),
        ]
    )
    delivery_address = forms.CharField(required=False)
    payment_on_get = forms.ChoiceField(
        choices=[
            ("0", "False"),
            ("1", "True"),
        ]
    )

    def clean_phone_number(self):
        data = self.cleaned_data["phone_number"]

        if not data.isdigit():
            raise forms.ValidationError("Номер телефону повинен містити лише цифри")

        pattern = re.compile(r"^\d{10}$")
        if not pattern.match(data):
            raise forms.ValidationError(
                "Невірни формат номеру. Введіть 10 цифр без коду країни"
            )
        return data

orders/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.contrib import messages
from django.shortcuts import redirect
from django.db import transaction
from django.forms import ValidationError

from .forms import CreateOrderForm
from orders.models import Order, OrderItem
from carts.models import Cart


@login_required
def create_order(request):
    if request.method == "POST":
        form = CreateOrderForm(data=request.POST)
        if form.is_valid():
            try:
                with transaction.atomic():
                    user = request.user
                    cart_items = Cart.objects.filter(user=user)

                    if cart_items.exists():
                        order = Order.objects.create(
                            user=user,
                            phone_number=form.cleaned_data["phone_number"],
                            requires_delivery=form.cleaned_data["requires_delivery"],
                            delivery_address=form.cleaned_data["delivery_address"],
                            payment_on_get=form.cleaned_data["payment_on_get"],
                        )
                        for cart_item in cart_items:
                            product = cart_item.product
                            name = cart_item.product.name
                            price = cart_item.products_price()
                            quantity = cart_item.quantity

                            if product.quantity < quantity:
                                raise ValidationError(
                                    f"Недостатня кількість товару {name} на складі\
                                    В наявності - {product.quantity}"
                                )

                            OrderItem.objects.create(
                                order=order,
                                product=product,
                                name=name,
                                price=price,
                                quantity=quantity,
                            )
                            product.quantity -= quantity
                            product.save()
                        # Видаляємо кошик
                        cart_items.delete()

                        messages.success(request, "Замовлення прийнято!")
                        return redirect("user:profile")

            except ValidationError as e:
                messages.success(request, str(e))
                return redirect("order:create_order")
    else:
        initial = {
            "first_name": request.user.first_name,
            "last_name": request.user.last_name,
        }
        form = CreateOrderForm(initial=initial)

    context = {
        "title": "Створити замовлення",
        "form": form,
        "order": True,
    }
    return render(
        request=request,
        template_name="orders/create_order.html",
        context=context,
    )

orders/templates/orders/create_order.html
{% extends 'base.html' %}
{% load static %}
{% load carts_tags %}

{% block content %}
    <div class="col-lg-8 mt-5 p-0" style="border: 3px solid black;">
        <div class="container-fluid p-0">
            <div class="bg-accordion p-4 rounded">
                <h3 class="text-center mb-4 fw-bold fs-1">Обраний товар</h3>
                <div class="container" id="cart-items-container">
                    <!-- Разметка корзины -->
                    {% user_carts request as carts %}
                    {% include "carts/includes/included_cart.html" %}
                    <!-- Конец разметки корзины -->
                </div>
                <div class="container p-0 mt-3">
                    <h3 class="card-title text-center fs-2">Детальніше о замовлені</h3>
                    <div class="card bg-accordion m-3" style="border: 3px solid black;">
                        <div class="card-body">
                            <form action="{% url "orders:create_order" %}" method="post" id="create_order_form">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-md-6 mt-3">
                                        <label for="id_first_name" class="form-label">І'мя*</label>
                                        <input type="text" class="form-control m-0 basket-bg"
                                               id="id_first_name" name="first_name"
                                               value="{% if form.first_name.value %}
                                                      {{ form.first_name.value }}{% endif %}"
                                               placeholder="Введыть ваше і'мя" required>
                                        {% if form.first_name.errors %}
                                            <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                                        {% endif %}
                                    </div>
                                    <div class="col-md-6 mt-3">
                                        <label for="id_last_name" class="form-label">Прізвище*</label>
                                        <input type="text" class="form-control m-0 basket-bg"
                                               id="id_last_name" name="last_name"
                                               value=" {% if form.last_name.value %}
                                                       {{ form.last_name.value }}{% endif %}"
                                               placeholder="Введыть ваше прізвище" required>
                                        {% if form.last_name.errors %}
                                            <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                                        {% endif %}
                                    </div>
                                    <div class="col-md-6 mt-3">
                                        <label for="id_phone_number" class="form-label">Номер
                                            телефону*:</label>
                                        <input type="text" class="form-control m-0 basket-bg"
                                               id="id_phone_number" name="phone_number"
                                               value="{% if form.phone_number.value %}
                                                      {{ form.phone_number.value }}{% endif %}"
                                               placeholder="(000) 000-0000" required>
                                        {% if form.phone_number.errors %}
                                            <div class="alert alert-danger alert-dismissible fade show">{{ form.phone_number.errors }}</div>
                                        {% endif %}
                                        <div class="alert alert-danger alert-dismissible fade show"
                                             style="display: none" id="phone_number_error">Неверный формат номера
                                        </div>
                                    </div>
                                    <div class="col-md-12 mt-3">
                                        <label for="delivery" class="form-label fs-5">Оберіть спосіб
                                            доставки:</label>
                                        <div class="form-check form-check-inline mx-2  fs-5">
                                            <input class="form-check-input" type="radio" name="requires_delivery"
                                                   id="delivery_np" value="1" checked>
                                            <label class="form-check-label" for="delivery_np">Новою поштою</label>
                                        </div>
                                        <div class="form-check form-check-inline mx-2  fs-5">
                                            <input class="form-check-input" type="radio" name="requires_delivery"
                                                   id="delivery_self" value="0">
                                            <label class="form-check-label" for="delivery_self">Самовивіз</label>
                                        </div>
                                    </div>
                                    <div class="mb-3" id="deliveryAddressField">
                                        <label for="id_delivery_address" class="form-label">Адрес доставки*:</label>
                                        <textarea class="form-control bg-login" id="id_delivery_address"
                                                  value="{% if form.delivery_address.value %}
                                                         {{ form.delivery_address.value }}{% endif %}"
                                                  name="delivery_address" rows="2"></textarea>
                                        {% if form.delivery_address.errors %}
                                            <div class="alert alert-danger alert-dismissible fade show">{{ form.delivery_address.errors }}</div>
                                        {% endif %}
                                    </div>
                                    {#                                    <div class="col-md-12 mt-3">#}
                                    {#                                        <label for="delivery" class="form-label fs-5">Оберіть спосіб доставки: </label>#}
                                    {#                                        <div class="form-check form-check-inline">#}
                                    {#                                            <input class="form-check-input mx-2 fs-5" type="radio" name="requires_delivery"#}
                                    {#                                                   id="id_requires_delivery" value="1" checked>#}
                                    {#                                            <label class="form-check-label" for="id_requires_delivery">Новою поштою</label>#}
                                    {#                                        </div>#}
                                    {#                                        <div class="form-check form-check-inline mx-2 fs-5">#}
                                    {#                                            <input class="form-check-input" type="radio" name="requires_delivery"#}
                                    {#                                                   id="id_requires_delivery" value="0">#}
                                    {#                                            <label class="form-check-label" for="id_requires_delivery">Самовивіз</label>#}
                                    {#                                        </div>#}
                                    {#                                    </div>#}
                                    {#                                    <div class="mb-3" id="deliveryAddressField">#}
                                    {#                                        <label for="id_delivery_address" class="form-label">Адрес#}
                                    {#                                            доставки:</label>#}
                                    {#                                        <textarea class="form-control bg-login" id="id_delivery_address"#}
                                    {#                                                  {% if form.delivery_address.value %}#}
                                    {#                                                  {{ form.delivery_address.value }}{% endif %}#}
                                    {#                                                  name="delivery_address" rows="2"></textarea>#}
                                    {#                                        {% if form.delivery_address.errors %}#}
                                    {#                                            <div class="alert alert-danger alert-dismissible fade show">{{ form.delivery_address.errors }}</div>#}
                                    {#                                        {% endif %}#}
                                    {#                                    </div>#}
                                    <div class="col-md-12 mb-3">
                                        <label class="form-label fs-5">Оберіть опосіб оплати:</label>
                                        <div class="form-check form-check-inline">
                                            <input class="form-check-input fs-5 mx-2" type="radio"
                                                   name="payment_on_get"
                                                   id="id_payment_on_get" value="0" checked>
                                            <label class="form-check-label" for="id_payment_on_get">Оплата
                                                картою</label>
                                        </div>
                                        <div class="form-check form-check-inline">
                                            <input class="form-check-input fs-5 mx-2" type="radio"
                                                   name="payment_on_get"
                                                   id="id_payment_on_get" value="1">
                                            <label class="form-check-label" for="id_payment_on_get">При
                                                отриманні</label>
                                        </div>
                                    </div>

                                </div>
                                <button type="submit" class="btn btn-product fs-4">Офортити
                                    замовлення
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}