carts/urls.py
from django.urls import path

from carts import views

app_name = "carts"

urlpatterns = [
    path("cart_add/", views.cart_add, name="cart_add"),
    path("cart_change/", views.cart_change, name="cart_change"),
    path("cart_remove/", views.cart_remove, name="cart_remove"),
]

goods/urls.py
from django.urls import path

from goods import views

app_name = "goods"

urlpatterns = [
    path("sreach/", views.CatalogView.as_view(), name="sreach"),
    path("<slug:category_slug>/", views.CatalogView.as_view(), name="index"),
    path("product/<slug:product_slug>/", views.ProductView.as_view(), name="product"),
]

house_of_tea/urls.py
from django.contrib import admin
from django.urls import path, include

from house_of_tea import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("goods.urls", namespace="catalog")),
    path("user/", include("users.urls", namespace="user")),
    path("cart/", include("carts.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main import views

app_name = "main"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("about/", views.AboutView.as_view(), name="about"),
]

goods/models.py
from django.db import models
from django.urls.base import reverse


class Categories(models.Model):
    name = models.CharField(
        max_length=50,
        unique=True,
    )

    slug = models.SlugField(
        max_length=255,
        unique=True,
        null=True,
        blank=True,
        verbose_name="URL",
    )

    class Meta:
        db_table = "Category"
        verbose_name = "Категрію"
        verbose_name_plural = "Категорії"
        ordering = ("id",)

    def __str__(self):
        return self.name


class Products(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name="Назва")
    slug = models.SlugField(
        max_length=255,
        unique=True,
        null=True,
        blank=True,
        verbose_name="URL",
    )

    description = models.TextField(null=True, blank=True, verbose_name="Опис")
    image = models.ImageField(
        upload_to="goods_images", null=True, blank=True, verbose_name="Зображення"
    )
    price = models.DecimalField(
        default=0.00, max_digits=7, decimal_places=2, verbose_name="Ціна"
    )
    discount = models.DecimalField(
        default=0.00, max_digits=4, decimal_places=2, verbose_name="Знижка у %"
    )
    quantity = models.PositiveIntegerField(default=0, verbose_name="Кількість товару")
    category = models.ForeignKey(to=Categories, on_delete=models.CASCADE)

    class Meta:
        db_table = "product"
        verbose_name = "Продукт"
        verbose_name_plural = "Продукти"
        ordering = ("id",)

    def __str__(self):
        return f"{self.name} - Кількість {self.quantity} - Ціна {self.price}"

    def get_absolute_url(self):
        return reverse("catalog:product", kwargs={"product_slug": self.slug})

    def product_id(self):
        return f"{self.id:05}"

    def sell_price(self):
        if self.discount:
            return round(self.price - (self.price * self.discount) / 100, 2)

        return self.price

goods/views.py
from django.views.generic import ListView, DetailView

from goods.models import Products
from goods.utils import q_search
from django.http import Http404


class CatalogView(ListView):
    model = Products
    template_name = "goods/catalog.html"
    context_object_name = "goods"
    paginate_by = 3

    def get_queryset(self):
        category_slug = self.kwargs.get("category_slug")
        on_sale = self.request.GET.get("on_sale", None)
        order_by = self.request.GET.get("order_by", None)
        min_range = self.request.GET.get("minRange", 1)
        max_range = self.request.GET.get("maxRange", 1000)
        query = self.request.GET.get("q", None)

        if category_slug == "all":
            goods = super().get_queryset().order_by("id")
        elif query or query == "":
            goods = q_search(query)
        else:
            goods = (
                super()
                .get_queryset()
                .filter(category__slug=category_slug)
                .filter(price__gte=min_range, price__lte=max_range)
            )
            if not goods.exists():
                raise Http404()

        if on_sale:
            goods = goods.filter(discount__gt=0)
        if order_by and order_by != "default":
            goods = goods.order_by(order_by)
        if not isinstance(goods, list):
            goods = goods.filter(price__gte=min_range, price__lte=max_range)

        return goods

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "HoT - Каталог"
        context["slug_url"] = self.kwargs.get("category_slug")
        return context


class ProductView(DetailView):
    template_name = "goods/product.html"
    slug_url_kwarg = "product_slug"
    context_object_name = "product"

    def get_object(self, queryset=None):
        product = Products.objects.get(slug=self.kwargs.get(self.slug_url_kwarg))
        return product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = self.object.name
        return context

goods/templates/goods/catalog.html
{% extends 'base.html' %}

{% load static %}
{% load goods_tags %}

{% block catalog_filter %}
    <div class="dropdown mb-2">
        <button class="btn sidebar-cat dropdown-toggle p-2" type="button" data-bs-toggle="dropdown"
                aria-expanded="false">
            Фільтри
        </button>

        <form action="
                {% if request.GET.q %}{% url 'catalog:sreach' %}{% else %}{% url 'catalog:index' slug_url %}" {% endif %}
              method="get" class="dropdown-menu sidebar-cat-menu" data-bs-theme="dark">
            <div class=" form-check range-filter-container">
                <label for="minRange">Мінімальна сума:</label>
                <input type="range" id="minRange" name="minRange" min="0" max="1000" value="1"
                       oninput="updateMinValue(this.value)">
                <span id="minValue">0</span> грн

                <label for="maxRange">Максимальна сума:</label>
                <input type="range" id="maxRange" name="maxRange" min="0" max="1000" value=""
                       oninput="updateMaxValue(this.value)">
                <span id="maxValue">1000</span> грн
            </div>

            <div class="form-check mx-3">
                <input class="form-check-input" type="checkbox" name="on_sale" id="flexCheckDefault"
                       value="on" {% if request.GET.on_sale == 'on' %} checked {% endif %}>
                {% if request.GET.q %}
                    <input type="hidden" name="q" value="request.GET.q">
                {% endif %}
                <label class="form-check-label" for="flexCheckDefault">
                    Акційні товари
                </label>
            </div>
            <p class=" mx-3 mt-3">Сортувати:</p>
            <div class="form-check mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault1"
                       value="default" {% if not request.GET.order_by or request.GET.order_by == 'default' %}
                       checked {% endif %}>
                <label class="form-check-label" for="flexRadioDefault1">
                    За замовчуванням
                </label>
            </div>
            <div class="form-check mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault2"
                       value="price" {% if request.GET.order_by == 'price' %} checked {% endif %}>
                <label class="form-check-label" for="flexRadioDefault2">
                    Від дешевих до дорогих
                </label>
            </div>
            <div class="form-check mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault3"
                       value="-price" {% if request.GET.order_by == '-price' %} checked {% endif %}>
                <label class="form-check-label" for="flexRadioDefault3">
                    Від дорогих до дешевих
                </label>
            </div>
            <button type="submit" class="btn btn-primary mx-3 mt-3">Застосувати</button>
        </form>
    </div>
{% endblock %}

{% block modal_cart %}
	{% include "includes/cart_button.html" %}
{% endblock %}

{% block content %}
    <div class="col-lg-10">
        {% include 'includes/notifications.html' %}
        <div class="row">
            {% for product in goods %}
                <!-- карта товара -->
                <div class="col-lg-4 p-4">
                    <div class="card border-primary rounded custom-shadow">
                        {% if product.image %}
                            <a href="{% url "catalog:product" product.slug %}">
                                <img src="{{ product.image.url }}" class="card-img-top bg-accordion"
                                     alt="{{ product.name }}">
                            </a>
                        {% else %}
                            <img src="{% static 'source/images/Not found image.png' %}"
                                 class="card-img-top bg-accordion" alt="{{ product.name }}">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title"><a class="order-link-button"
                                                      href="{% url "catalog:product" product.slug %}">{{ product.name }}</a>
                            </h5>
                            <p class="card-text text-truncate">{{ product.description|truncatechars:35 }}</p>
                            <p class="product_id">id: {{ product.product_id }}</p>
                            <div class="d-flex justify-content-between">
                                {% if product.discount %}
                                    <p>50 г</p>
                                    <p><s>{{ product.price }}</s> грн</p>
                                    <p><strong>{{ product.sell_price }} грн</strong></p>
                                    <span class="badge bg-warning text-dark">Скидка {{ product.discount }} %</span>
                                {% else %}
                                    <p>50 г</p>
                                    <p><strong>{{ product.price }} грн</strong></p>
                                {% endif %}
                                <!-- <p><strong>100.00 $</strong></p> -->
                                <a href="{% url 'carts:cart_add' %}" class="btn basket-add add-to-cart"
                                data-product-id={{ product.id }}>
                                    {% csrf_token %}
                                    <img class="mx-1" src="{% static 'source/icons/cart-plus.svg' %}" alt="Catalog Icon"
                                         width="32" height="32">
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}


        </div>
        <!-- пагінация -->
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center my-4">
                <div class="d-flex pagination-nav">

                    <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                        <a class="page-link" href="{% if page_obj.has_previous %}
                        ?{% change_params page=page_obj.previous_page_number %}
                        {% else %}#{% endif %}">Назад</a>
                    </li>

                    {% for page in page_obj.paginator.page_range %}
                        {% if page >= page_obj.number|add:-2 and page <= page_obj.number|add:2 %}
                            <li class="page-item {% if page_obj.number == page %} active {% endif %} ">
                                <a class="page-link" href="?{% change_params page=page %}">{{ page }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}

                    <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
                        <a class="page-link" href="{% if page_obj.has_next %}
                        ?{% change_params page=page_obj.next_page_number %}
                        {% else %}#{% endif %}">Далі</a>
                    </li>

                </div>
            </ul>
        </nav>
    </div>
{% endblock %}

goods/templates/goods/product.html
{% extends 'base.html' %}

{% load static %}

{% block modal_cart %}
    {% include "includes/cart_button.html" %}
{% endblock %}

{% block catalog_filter %}
    <div class="dropdown mb-2">
        <button class="btn sidebar-cat dropdown-toggle p-2" type="button" data-bs-toggle="dropdown"
                aria-expanded="false">
            Фільтри
        </button>

        <form action="" method="get" class="dropdown-menu sidebar-cat-menu" data-bs-theme="dark">
            <div class=" form-check range-filter-container">
                <label for="minRange">Мінімальна сума:</label>
                <input type="range" id="minRange" name="minRange" min="0" max="1000" value="1"
                       oninput="updateMinValue(this.value)">
                <span id="minValue">0</span> $

                <label for="maxRange">Максимальна сума:</label>
                <input type="range" id="maxRange" name="maxRange" min="0" max="1000" value="1000"
                       oninput="updateMaxValue(this.value)">
                <span id="maxValue">1000</span> $
            </div>

            <div class="form-check mx-3">
                <input class="form-check-input" type="checkbox" name="on_sale" id="flexCheckDefault"
                       value="on">
                <input type="hidden" name="q" value="request.GET.q">
                <label class="form-check-label" for="flexCheckDefault">
                    Акційні товари
                </label>
            </div>
            <p class=" mx-3 mt-3">Сортувати:</p>
            <div class="form-check mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault1"
                       value="default" checked>
                <label class="form-check-label" for="flexRadioDefault1">
                    За замовчуванням
                </label>
            </div>
            <div class="form-check mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault2"
                       value="price">
                <label class="form-check-label" for="flexRadioDefault2">
                    Від дешевих до дорогих
                </label>
            </div>
            <div class="form-check mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault3"
                       value="-price">
                <label class="form-check-label" for="flexRadioDefault3">
                    Від дорогих до дешевих
                </label>
            </div>
            <button type="submit" class="btn btn-primary mx-3 mt-3">Застосувати</button>
        </form>
    </div>
{% endblock %}

{% block content %}
    <div class="col-lg-10 mb-5">
        {% include 'includes/notifications.html' %}
        <!-- карта товара -->
        <div class="col-lg-8">
            <div class="container">
                <div class="card custom-shadow card-body p-2">
                    <div class="col-md-4 m-2">
                        <img src="{{ product.image.url }}" alt="" class="img-fluid"
                             data-bs-toggle="modal" data-bs-target="#imageModal1">
                    </div>
                    <div class="col-md-4 mx-2 m">
                        <p class="product_id mb-0">id: {{ product.product_id }}</p>
                    </div>
                    <!-- Увеличить изображение в модальном окне -->
                    <div class="modal fade" id="imageModal1" tabindex="-1"
                         aria-labelledby="imageModal1Label" aria-hidden="true">
                        <div class="modal-dialog modal-lg">
                            <div class="modal-content bg-product text-white">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="imageModal1Label">{{ product.name }}</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                                            aria-label="Закрыть"></button>
                                </div>
                                <div class="modal-body">
                                    <img src="{{ product.image.url }}" class="img-fluid"
                                         alt="Изображение 1">
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Описание товара -->
                    <div class="mx-2">
                        <p class="card-text fs-5 m-0">50 г</p>
                        <p class="card-text fs-4 mb-0">Ціна: <strong>{{ product.sell_price }} грн</strong></p>
                        <h5 class="card-title">{{ product.name }}</h5>
                        <p class="card-text fs-4">{{ product.description }}</p>
                        <a href="{% url 'cart:cart_add' %}" class="btn-product fs-3 add-to-cart"
                           data-product-id={{ product.id }}>{% csrf_token %}Добавить в корзину</a>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}