goods/urls.py
from django.urls import path

from goods import views

app_name = "goods"

urlpatterns = [
    path("sreach/", views.CatalogView.as_view(), name="sreach"),
    path("<slug:category_slug>/", views.CatalogView.as_view(), name="index"),
    path("product/<slug:product_slug>/", views.ProductView.as_view(), name="product"),
]

house_of_tea/urls.py
from django.contrib import admin
from django.urls import path, include

from house_of_tea import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("goods.urls", namespace="catalog")),
    path("user/", include("users.urls", namespace="user")),
    path("cart/", include("carts.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main import views

app_name = "main"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("about/", views.AboutView.as_view(), name="about"),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users import views

app_name = "users"

urlpatterns = [
    path("login/", views.UserLoginView.as_view(), name="login"),
    path("registration/", views.UserRegistrationView.as_view(), name="registration"),
    path("profile/", views.UserProfileView.as_view(), name="profile"),
    path("users-cart/", views.UsersCartView.as_view(), name="users_cart"),
    path("logout/", LogoutView.as_view(next_page="/"), name="logout"),
]

orders/models.py
from django.db import models

from users.models import User
from goods.models import Products


class OrderItemQuerySet(models.QuerySet):
    def total_price(self):
        return sum(cart.products_price() for cart in self)

    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0


class Order(models.Model):
    user = models.ForeignKey(
        to=User, on_delete=models.SET_DEFAULT, blank=True, null=True, default=None
    )
    created_timestamp = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата замовлення"
    )
    phone_number = models.CharField(
        max_length=20, verbose_name="Номер телефону замовника"
    )
    requires_delivery = models.BooleanField(
        default=False, verbose_name="Потрібна доставка"
    )
    delivery_address = models.TextField(
        blank=True, null=True, default="Адреса доставки"
    )
    payment_on_get = models.BooleanField(
        default=False, verbose_name="Оплата при отриманні"
    )
    is_paid = models.BooleanField(default=False, verbose_name="Оплачено")
    status = models.CharField(
        max_length=50, default="В обробці", verbose_name="Статус замовлення"
    )

    class Meta:
        db_table = "order"
        verbose_name = "Заказ"
        verbose_name_plural = "Закази"
        ordering = ("id",)

    def __str__(self):
        return f"Замовлення № {self.pk} | Замовник {self.user.first_name} {self.user.last_name}"


class OrderItem(models.Model):
    order = models.ForeignKey(
        to=Order, on_delete=models.CASCADE, verbose_name="Замовлення"
    )
    product = models.ForeignKey(
        to=Products, on_delete=models.SET_DEFAULT, default=None, blank=True, null=True
    )
    name = models.CharField(max_length=150, verbose_name="Назва")
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Ціна")
    quantity = models.PositiveIntegerField(default=0, verbose_name="Кількість")
    created_timestamp = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата продажу"
    )

    class Meta:
        db_table = "order_item"
        verbose_name = "Продані товари"
        verbose_name_plural = "Продані товари"
        ordering = ("id",)

    objects = OrderItemQuerySet.as_manager()

    def product_price(self):
        return round(self.price * self.quantity, 2)

    def __str__(self):
        return f"Замовлення {self.name} | Номер № {self.order.pk}"

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    image = models.ImageField(
        upload_to="users_image",
        null=True,
        blank=True,
        verbose_name="Аватар",
    )

    class Meta:
        db_table = "user"
        verbose_name = "Користувач"
        verbose_name_plural = "Користувачі"

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import (
    AuthenticationForm,
    UserCreationForm,
    UserChangeForm,
)
from users.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField()
    password = forms.CharField()

    class Meta:
        model = User
        fields = (
            "username",
            "password",
        )


class UserRegisterForm(UserCreationForm):
    first_name = forms.CharField()
    email = forms.CharField()
    last_name = forms.CharField()
    password1 = forms.CharField()
    username = forms.CharField()
    password2 = forms.CharField()

    class Meta:
        model = User
        fields = (
            "first_name",
            "email",
            "last_name",
            "password1",
            "username",
            "password2",
        )


class ProfileForm(UserChangeForm):
    image = forms.ImageField(required=False)
    first_name = forms.CharField()
    email = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()

    class Meta:
        model = User
        fields = (
            "image",
            "first_name",
            "email",
            "last_name",
            "username",
        )

users/views.py
from django.contrib import auth, messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.db.models import Prefetch
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, TemplateView

from users.forms import UserLoginForm, UserRegisterForm, ProfileForm
from django.contrib.auth.decorators import login_required
from carts.models import Cart
from orders.models import Order, OrderItem


class UserLoginView(LoginView):
    template_name = "users/login.html"
    form_class = UserLoginForm

    def get_success_url(self):
        redirect_page = self.request.POST.get("next", None)
        if redirect_page and redirect_page != reverse_lazy("users:login"):
            return redirect_page
        return reverse_lazy("main:index")

    def form_valid(self, form):
        session_key = self.request.session.session_key
        user = form.get_user()
        if user:
            auth.login(self.request, user)
            if session_key:
                forgot_key = Cart.objects.filter(user=user)
                if forgot_key.exists():
                    forgot_key.delete()
                Cart.objects.filter(session_key=session_key).update(user=user)

                messages.success(
                    self.request, f"{user.username}, Вас було авторизовано."
                )
                return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "HoT - Авторизація"
        return context


class UserRegistrationView(CreateView):
    template_name = "users/registration.html"
    form_class = UserRegisterForm
    success_url = reverse_lazy("main:index")

    def form_valid(self, form):
        session_key = self.request.session.session_key
        user = form.instance

        if user:
            form.save()
            auth.login(self.request, user)
        if session_key:
            Cart.objects.filter(session_key=session_key).update(user=user)

        messages.success(
            self.request,
            f"{user.username}, Ви успішно зареєструвалися та авторизовано на сайты.",
        )
        return HttpResponseRedirect(self.success_url)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "HoT - Реестрація"
        return context


class UserProfileView(LoginRequiredMixin, UpdateView):
    template_name = "users/profile.html"
    form_class = ProfileForm
    success_url = reverse_lazy("users:profile")

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        messages.success(self.request, f"Оновлено")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.success(self.request, f"Виникла помилка")
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "HoT - Мій профіль"
        context["orders"] = (
            Order.objects.filter(user=self.request.user)
            .prefetch_related(
                Prefetch(
                    "orderitem_set",
                    queryset=OrderItem.objects.select_related("product"),
                )
            )
            .order_by("-id")
        )
        return context


class UsersCartView(TemplateView):
    template_name = "users/users_cart.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "HoT - Кошик"
        return context

users/templates/users/profile.html
{% extends 'base.html' %}

{% load static %}

{% block modal_cart %}
    {% include "includes/cart_button.html" %}
{% endblock %}

{% block content %}
    <div class="col-lg-8 mt-5 p-0" style="border: 3px solid black;">
        <div class="container-fluid p-0">
            <div class="accordion" id="accordionExample">
                <!-- Профиль -->
                <div class="accordion-item border-0">
                    <h2 class="accordion-header bg-accordion" id="heading1">
                        <button class="accordion-button" type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapseprofile" aria-expanded="false" aria-controls="collapseprofile">
                            Особиста інформація Користувача
                        </button>
                    </h2>
                    <div id="collapseprofile" class="accordion-collapse collapse show" aria-labelledby="heading1"
                         data-bs-parent="#accordionExample">
                        <div class="accordion-body bg-accordion">
                            <div class="px-3">
                                <form action="{% url 'users:profile' %}" method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {% include 'includes/notifications.html' %}
                                    <div class="row">
                                        <div class="col-md-3 mb-3 text-center">
                                            {% if user.image %}
                                                <img src="{{ user.image.url }}"
                                                     alt="Аватар пользователя" class="img-fluid rounded-circle"
                                                     style="max-width: 100px;">
                                            {% else %}
                                                <img src="{% static 'source/images/baseavatar.jpg' %}"
                                                     alt="Аватар пользователя" class="img-fluid rounded-circle"
                                                     style="max-width: 100px;">
                                            {% endif %}

                                            <input type="file" class="form-control mt-3" id="id_image"
                                                   accept="image/" name="image">
                                            {% if form.image.errors %}
                                                <div class="alert alert-danger alert-dismissible fade show">{{ form.image.errors }}</div>
                                            {% endif %}
                                        </div>
                                        <div class="col-md-9">
                                            <div class="row">
                                                <div class="row">
                                                    <div class="col-md-6 mb-3">
                                                        <label for="id_first_name"
                                                               class="form-label">І'мя*</label>
                                                        <input type="text"
                                                               class="form-control bg-input bg-login"
                                                               id="id_first_name" placeholder="Введіть ваше ім'я"
                                                               value="{{ form.first_name.value }}"
                                                               name="first_name" required>
                                                        {% if form.first_name.errors %}
                                                            <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                                                        {% endif %}
                                                    </div>
                                                    <div class="col-md-6 mb-3">
                                                        <label for="id_email" class="form-label">Email*</label>
                                                        <input type="email"
                                                               class="form-control bg-input bg-login"
                                                               id="id_email" name="email"
                                                               value="{{ form.email.value }}"
                                                               placeholder="Введіть вашу електрону пошту"
                                                               required>
                                                        {% if form.email.errors %}
                                                            <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                                                        {% endif %}
                                                    </div>
                                                    <div class="col-md-6 mb-3">
                                                        <label for="id_last_name"
                                                               class="form-label">Прізвище*</label>
                                                        <input type="text" class="form-control bg-login"
                                                               id="id_last_name" name="last_name"
                                                               value="{{ form.last_name.value }}"
                                                               placeholder="Введіть ваше прізвище" required>
                                                        {% if form.last_name.errors %}
                                                            <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                                                        {% endif %}
                                                    </div>
                                                    <div class="col-md-6 mb-3">
                                                        <label for="id_username" class="form-label">По
                                                            батькові*</label>
                                                        <input type="text"
                                                               class="form-control bg-input bg-login"
                                                               id="id_username" name="username"
                                                               value="{{ form.username.value }}"
                                                               placeholder="Введіть ваше і'мя по батькові"
                                                               required>
                                                        {% if form.username.errors %}
                                                            <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                                                        {% endif %}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div style="display: flex; justify-content: center">
                                            <button type="submit"
                                                    class="btn btn-product mb-2 fs-4">Зберегти
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- закази -->
                <div class="accordion-item border-0">
                    <h2 class="accordion-header bg-accordion" id="heading1">
                        <button class="accordion-button" type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapseorders" aria-expanded="false" aria-controls="collapseorders">
                            Мої замовлення
                        </button>
                    </h2>
                    <div id="collapseorders" class="accordion-collapse collapse show" aria-labelledby="heading1"
                         data-bs-parent="#accordionExample">
                        <div class="accordion-body bg-accordion">
                            <div class="px-3">
                                <!-- Разметка заказов -->
                                <div class="container">
                                    <div class="accordion" id="accordionExample1">
                                        {% for order in orders %}
                                            <div class="accordion-item">
                                                <h2 class="accordion-header bg-accordion-order"
                                                    id="heading{{ order.id }}">
                                                    <button class="accordion-button fs-5 {% if order != orders.0 %}collapsed{% endif %}"
                                                            type="button"
                                                            data-bs-toggle="collapse"
                                                            data-bs-target="#collapse{{ order.id }}"
                                                            aria-expanded="false"
                                                            aria-controls="collapse{{ order.id }}">
                                                        Замовлення № {{ order.id }} - {{ order.created_timestamp }} |
                                                        Статус:
                                                        <strong class="mx-2"> {{ order.status }}</strong>
                                                    </button>
                                                </h2>
                                                <div id="collapse{{ order.id }}"
                                                     class="accordion-collapse collapse {% if order == orders.0 %}show{% endif %}"
                                                     aria-labelledby="heading{{ order.id }}"
                                                     data-bs-parent="#accordionExample1">
                                                    <div class="accordion-body bg-accordion-order">
                                                        <table class="table table-dark table-hover">
                                                            <thead>
                                                            <tr>
                                                                <th>Товар</th>
                                                                <th>Кількість</th>
                                                                <th>Ціна</th>
                                                                <th>Загальна вартість</th>
                                                            </tr>
                                                            </thead>
                                                            <tbody>
                                                            {% for item in order.orderitem_set.all %}
                                                                <tr>
                                                                    <td><a class="text-white"
                                                                           href="{% url 'goods:product' item.product.slug %}">{{ item.name }}</a>
                                                                    </td>
                                                                    <td>{{ item.quantity }}</td>
                                                                    <td>{{ item.price }}</td>
                                                                    <td>{{ item.products_price }}</td>

                                                                </tr>
                                                            {% endfor %}

                                                            </tbody>
                                                        </table>
                                                        <div class="d-flex justify-content-between">
                                                            <p><strong>Разом:</strong></p>
                                                            <p><strong>255.00 $</strong></p>

                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                                <!-- Закончилась разметка заказов -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/registration.html
{% extends 'base.html' %}

{% load static %}

{% block modal_cart %}
	{% include "includes/cart_button.html" %}
{% endblock %}

{% block content %}
    <div class="col-lg-8">
        {% include 'includes/notifications.html' %}
        <div class="row">
            <div class="container mt-5">
                <div class="row justify-content-center">
                    <div class="col-md-9 bg-login p-4 mb-4 mx-3 rounded">
                        <h2 class="text-center mb-4 fw-bold">Реєстрація</h2>
                        <form action="{% url 'users:registration' %}" method="post">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-6 mb-3">
                                    <label for="id_first_name" class="form-label">І'мя*</label>
                                    <input type="text" class="form-control bg-input bg-login" id="id_first_name"
                                           value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
                                           placeholder="Введіть ваше ім'я" name="first_name" required>
                                    {% if form.first_name.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                                    {% endif %}
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label for="id_email" class="form-label">Email*</label>
                                    <input type="email" class="form-control bg-input bg-login" id="id_email"
                                           value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
                                           placeholder="Введіть вашу електрону пошту" name="email" required>
                                    {% if form.email.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                                    {% endif %}
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label for="id_last_name" class="form-label">Прізвище*</label>
                                    <input type="text" class="form-control bg-input bg-login" id="id_last_name"
                                           value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"
                                           placeholder="Введіть ваше прізвище" name="last_name" required>
                                    {% if form.last_name.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                                    {% endif %}
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label for="id_password1" class="form-label">Пароль*</label>
                                    <input type="password" class="form-control bg-input bg-login" id="id_password1"
                                           value="{% if form.password1.value %}{{ form.password1.value }}{% endif %}"
                                           placeholder="Введіть пароль" name="password1" required>
                                    {% if form.password1.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.password1.errors }}</div>
                                    {% endif %}
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label for="id_username" class="form-label">І'мя користувача*</label>
                                    <input type="text" class="form-control bg-input bg-login" id="id_username"
                                           value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                                           placeholder="Введіть ваше і'мя користувача" name="username" required>
                                    {% if form.username.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                                    {% endif %}
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label for="id_password2" class="form-label">Пароль*</label>
                                    <input type="password" class="form-control bg-input bg-login" id="id_password2"
                                           placeholder="Повторіть пароль" name="password2" required>
                                    {% if form.password2.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.password2.errors }}</div>
                                    {% endif %}
                                </div>
                            </div>
                            <button type="submit" class="btn btn-product fs-4">Зареєструватися</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/users_cart.html
{% extends 'base.html' %}
{% load static %}
{% load carts_tags %}

{% block content %}
    {% user_carts request as carts %}
    <div class="col-lg-8 mt-5 p-0" style="border: 3px solid black;">
        <div class="container-fluid p-0">
            <div class="bg-accordion p-4 rounded">
                <h3 class="text-center mb-4 fw-bold fs-1">Кошик</h3>
                <div class="container" id="cart-items-container">
                        <!-- Разметка корзины -->
                        {% include 'carts/includes/included_cart.html' %}
                        <!-- Конец разметки корзины -->
                </div>
            </div>
        </div>
    </div>
{% endblock %}