goods/urls.py
from django.urls import path

from goods import views

app_name = "goods"

urlpatterns = [
    path("sreach/", views.CatalogView.as_view(), name="sreach"),
    path("<slug:category_slug>/", views.CatalogView.as_view(), name="index"),
    path("product/<slug:product_slug>/", views.ProductView.as_view(), name="product"),
]

house_of_tea/urls.py
from django.contrib import admin
from django.urls import path, include

from house_of_tea import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("goods.urls", namespace="catalog")),
    path("user/", include("users.urls", namespace="user")),
    path("cart/", include("carts.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main import views

app_name = "main"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("about/", views.AboutView.as_view(), name="about"),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users import views

app_name = "users"

urlpatterns = [
    path("login/", views.UserLoginView.as_view(), name="login"),
    path("registration/", views.UserRegistrationView.as_view(), name="registration"),
    path("profile/", views.UserProfileView.as_view(), name="profile"),
    path("users-cart/", views.UsersCartView.as_view(), name="users_cart"),
    path("logout/", LogoutView.as_view(next_page="/"), name="logout"),
]

templates/base.html
{% load static %}
{% load goods_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'source/styles/mycss.css' %}">
    <title>{{ title }}</title>
</head>

<body>
<header>
    <nav class="navbar navbar-expand-lg p-0 pt-1">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'main:index' %}">HoT</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'main:index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/products/catalog.html">Акції</a>
                    </li>
                    <li class="nav-item">
                        <div class="dropdown">
                            <a class="nav-link drop-active" href="#" role="button" data-bs-toggle="dropdown"
                               aria-expanded="false">
                                Мії акаунт
                            </a>
                            <ul class="dropdown-menu">
                                {% if user.is_authenticated %}
                                    <li><a class="dropdown-item nav-link" href="{% url 'users:profile' %}">Особстий
                                        кабінет</a></li>
                                {% endif %}
                                <li><a class="dropdown-item nav-link" href="{% url 'users:users_cart' %}">Кошик</a></li>
                                {% if user.is_staff or user.is_admin %}
                                    <li>
                                    <a class="dropdown-item nav-link" href="{% url 'admin:index' %}">Адмін панель</a>
                                {% endif %}
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:about' %}">Більше про нас</a>
                    </li>
                </ul>
                {% if not user.is_authenticated %}
                    <a href="{% url 'users:login' %}">
                        <img class="logio-logo mx-2"
                             src="{% static 'source/images/login_26dp_000000_FILL0_wght400_GRAD0_opsz24.png' %}"
                             alt="" style="width: 35px;">
                    </a>
                {% else %}
                    <form action="{% url 'users:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" style="border: none; background: none;" class="p-0">
                            <img class="logio-logo mx-2"
                                 src="{% static 'source/images/logout_26dp_000000_FILL0_wght400_GRAD0_opsz24.png' %}"
                                 alt="Logout" style="width: 35px;">
                        </button>
                    </form>
                {% endif %}
                <form class="d-flex" role="search" action="{% url 'catalog:sreach' %}" method="get">
                    <input class="form-control me-2 p-0 px-1" style="width: 200px;" type="search"
                           placeholder="Search" aria-label="Search" name="q">
                    <button class="btn btn-outline-success p-0 px-1" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
</header>

<section>
    <div class="container-fluid mt-4">
        <div class="row">


            <div class="col-lg-2 sidebar-menu">

                <div class="dropdown mb-2">
                    <button class="btn sidebar-cat dropdown-toggle p-2" type="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                        Каталог
                        <img class="mx-1" src="{% static 'source/icons/grid-fill.svg' %}" alt="Catalog Icon" width="16"
                             height="16">
                    </button>
                    <ul class="dropdown-menu sidebar-cat-menu" data-bs-theme="dark">
                        {% tag_categories as categories %}
                        {% for category in categories %}
                            <li><a class="dropdown-item text-dark"
                                   href="{% url 'catalog:index' category.slug %}">{{ category.name }}</a></li>
                        {% endfor %}

                    </ul>
                </div>
                <!-- Разметка модального окна корзины -->
                {% block modal_cart %}

                {% endblock %}
                <!-- Закончилась разметка модального окна -->

                {% block catalog_filter %}{% endblock %}
            </div>

            {% block content %}{% endblock %}
        </div>
    </div>
</section>

{% block footer %}{% endblock %}

<script src="{% static 'source/js/jquery/jquery-3.7.0.min.js' %}"></script>
<script src="{% static 'source/js/jquery-ajax.js' %}"></script>
<script src="{% static 'source/js/app.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
</body>

</html>